Repository DeveloperAcademy-POSTECH/MacC-Team-IKU, pull requests merged in 2022-11, with the labels that each got.

#7 [D2] 프로젝트에 사용될 폰트 추가
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/App/Info.plist
  IKU/IKU/Data/Font/NEXON_Lv1_Gothic_OTF.otf
  IKU/IKU/Data/Font/NEXON_Lv1_Gothic_OTF_Bold.otf
  IKU/IKU/Data/Font/NEXON_Lv1_Gothic_OTF_Light.otf
  IKU/IKU/Extension/UIFont+Extension.swift
Labels: ✨Feature

#11 [D5] 시작 버튼, 동영상 재생
  IKU/IKU/Views/PlayerView.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
Labels: ✨Feature

#12 [D5] 영상에서 사진을 선택하는 기능
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/App/SceneDelegate.swift
  IKU/IKU/Views/NavigationViewController.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
Labels: ✨Feature

#16 [D2] Complete HistoryView UI
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Data/StrabismusLog.swift
  IKU/IKU/Resource/Color.xcassets/ikuBackground.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuBlue.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuCalendarWeekend.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuCalendarWeeklyTitle.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuDarkGray.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuLightGray.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuOrange.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuYellow.colorset/Contents.json
  IKU/IKU/Views/HistoryViewController.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVCalendarContentViewController.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVCalendarDayView.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVCalendarMonthContentViewController.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVCalendarMonthView.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVMonth.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView+Extension.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView.swift
  IKU/IKU/Views/ViewModule/IKUChartView.swift
Labels: ✨Feature

#15 [D5] 시작 버튼 애니메이션, UI 변경
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Views/PlayButton.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView.swift
Labels: ✨Feature

#18 [D5] 사진 선택 화면 navigation 적용
  IKU/IKU/Views/NavigationViewController.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
Labels: ✨Feature

#19 [D5] 사진 선택 화면 배경 색상 적용
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Views/GradientView.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
Labels: ✨Feature

#22 [D5] 사진 선택 화면 안내 문구
  IKU/IKU/Views/SelectPhotoViewController.swift
Labels: ✨Feature

#36 [D2] ARScene에 필요한 Source 추가
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/App/Info.plist
  IKU/IKU/Manager/ARCapture/ARAssetWriter.swift
  IKU/IKU/Manager/ARCapture/ARCapture.swift
  IKU/IKU/Manager/ARCapture/ARFrameGenerator.swift
  IKU/IKU/Manager/ARSceneManager.swift
  IKU/IKU/Resource/Models.scnassets/coordinateOrigin.scn
  IKU/IKU/Resource/popSound.mp3
  IKU/IKU/Views/CoverTestViewController.swift
Labels: ✨Feature

#33 [D5] StoryView 생성 (SF버젼)
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/App/SceneDelegate.swift
  IKU/IKU/Views/StoryView.swift
Labels: ✨Feature

#55 [D1] enum Eye 추가
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Data/Eye.swift
Labels: ✨Feature

#40 [D5] 영구저장소 자료구조 설계
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Manager/PersistenceManager.swift
  IKU/PersistenceTest/PersistenceTest.swift
Labels: ✨Feature

#53 [D5] 탭바 중 사시검사탭과 View 연결하는 로직 구현
  IKU/IKU/App/SceneDelegate.swift
Labels: ✨Feature

#60 [D1] 결과 저장 Entity 생성
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Data/DataPlaceholder.swift
  IKU/IKU/Data/MeasurementResult.swift
Labels: ✨Feature

#59 [D2] ViewController 연결
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/App/SceneDelegate.swift
  IKU/IKU/Data/StrabismusLog.swift
  IKU/IKU/Extension/UIView+Extension.swift
  IKU/IKU/Extension/UIViewController+Extension.swift
  IKU/IKU/Manager/ARCapture/ARAssetWriter.swift
  IKU/IKU/Manager/ARCapture/ARCapture.swift
  IKU/IKU/Manager/ARSceneManager.swift
  IKU/IKU/Manager/VideoManager.swift
  IKU/IKU/Storyboard/Base.lproj/Main.storyboard
  IKU/IKU/Views/CoverTestViewController.swift
  IKU/IKU/Views/CoverTestViewModel.swift
  IKU/IKU/Views/HistoryViewController.swift
  IKU/IKU/Views/InformationViewController.swift
  IKU/IKU/Views/ResultViewController.swift
  IKU/IKU/Views/ScrubberView.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
  IKU/IKU/Views/ViewModule/IKUChartView.swift
Labels: ✨Feature

#51 [D3] StoryView에서 눈 선택하는 로직 구현
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Resource/Assets.xcassets/lefteye.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/lefteye.imageset/lefteye.png
  IKU/IKU/Resource/Assets.xcassets/righteye.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/righteye.imageset/righteye.png
  IKU/IKU/Resource/Color.xcassets/ikuEyeSelectBackground.colorset/Contents.json
  IKU/IKU/Views/SelectWhichEyeView.swift
  IKU/IKU/Views/StoryView.swift
Labels: ✨Feature

#67 Remove Enum Eyes
  IKU/IKU/Manager/ARSceneManager.swift
  IKU/IKU/Manager/PHPhotoManager.swift
  IKU/IKU/Views/SelectWhichEyeView.swift
Labels: 🐞Bug

#65 [D2] ProfileUI 구현
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/App/SceneDelegate.swift
  IKU/IKU/Storyboard/HistoryVC.storyboard
  IKU/IKU/Views/ProfileViewController.swift
Labels: ✨Feature

#69 [D5] PersistenceManager의 이름을 SQLiteService로 변경
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Manager/SQLiteService.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
  IKU/PersistenceTest/PersistenceTest.swift
Labels: ♻️Refactoring

#74 [D5] 사시각 결과를 JSON으로 저장하는 객체 생성
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU.xcodeproj/xcshareddata/xcschemes/IKU.xcscheme
  IKU/IKU.xcodeproj/xcshareddata/xcschemes/PersistenceTest.xcscheme
  IKU/IKU/Manager/JSONService.swift
  IKU/IKU/Manager/PersistenceManager.swift
  IKU/PersistenceTest/JSONServiceTest.swift
Labels: ✨Feature

#71 [D1] 값 Dictionary 이름 변경
  IKU/IKU/App/SceneDelegate.swift
  IKU/IKU/Manager/ARSceneManager.swift
  IKU/IKU/Views/CoverTestViewController.swift
  IKU/IKU/Views/CoverTestViewModel.swift
  IKU/IKU/Views/HistoryViewController.swift
  IKU/IKU/Views/ScrubberView.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
  IKU/IKU/Views/StoryView.swift
Labels: ♻️Refactoring

#75 [D1] HistoryView UI Update
  IKU/IKU/Views/CoverTestViewController.swift
  IKU/IKU/Views/CoverTestViewModel.swift
  IKU/IKU/Views/HistoryViewController.swift
  IKU/IKU/Views/ResultViewController.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
  IKU/IKU/Views/ViewModule/IKUChartView.swift
Labels: ♻️Refactoring

#80 [D2] Persistence manager 구현
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Manager/PersistenceManager.swift
  IKU/PersistenceTest/PersistenceManagerTest.swift
Labels: ✨Feature

#79 [D2] VideoURLService 구현
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Manager/PersistenceManager.swift
  IKU/IKU/Manager/VideoURLService.swift
  IKU/PersistenceTest/PersistenceManagerTest.swift
  IKU/PersistenceTest/VideoURLServiceTest.swift
Labels: ✨Feature

#81 [D1] 사시 검사 및 각도 계산 결과 표시
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/App/SceneDelegate.swift
  IKU/IKU/Extension/Double+Extension.swift
  IKU/IKU/Manager/ARSceneManager.swift
  IKU/IKU/Views/CoverTestViewController.swift
  IKU/IKU/Views/HistoryViewController.swift
  IKU/IKU/Views/ResultViewController.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
  IKU/IKU/Views/StoryView.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVCalendarTouchController.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView+Extension.swift
Labels: ✨Feature

#91 [D1] TextField구현
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Views/ProfileViewController.swift
Labels: ✨Feature

#94 [D1] 닉네임 글자수 제한
  IKU/IKU/Views/ProfileViewController.swift
  IKU/IKU/Views/StoryView.swift
Labels: ♻️Refactoring

#96 [D2] 영구저장소에서 삭제 함수 구현
  IKU/IKU/Manager/PersistenceManager.swift
  IKU/IKU/Manager/SQLiteService.swift
  IKU/IKU/Manager/VideoURLService.swift
  IKU/PersistenceTest/PersistenceManagerTest.swift
  IKU/PersistenceTest/SQLiteServiceTest.swift
  IKU/PersistenceTest/VideoURLServiceTest.swift
Labels: ✨Feature

#95 [D1] 검사 데이터 저장 및 조회
  IKU/IKU/App/SceneDelegate.swift
  IKU/IKU/Data/TestGuideString.swift
  IKU/IKU/Views/CoverTestViewModel.swift
  IKU/IKU/Views/HistoryViewController.swift
  IKU/IKU/Views/ResultViewController.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVCalendarContentViewController.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVCalendarDayView.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVCalendarMonthContentViewController.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVCalendarView.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVDate.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView+Extension.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView.swift
Labels: ✨Feature

#101 [D1] HistoryView와 ResultView를 연결했습니다.
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/App/Info.plist
  IKU/IKU/App/SceneDelegate.swift
  IKU/IKU/Manager/ARCapture/ARAssetWriter.swift
  IKU/IKU/Manager/ARCapture/ARCapture.swift
  IKU/IKU/Resource/Color.xcassets/ikuCautionColor.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuSafeColor.colorset/Contents.json
  IKU/IKU/Storyboard/Base.lproj/Main.storyboard
  IKU/IKU/Views/CoverTestViewController.swift
  IKU/IKU/Views/CoverTestViewModel.swift
  IKU/IKU/Views/HistoryListViewController.swift
  IKU/IKU/Views/HistoryViewController.swift
  IKU/IKU/Views/ResultViewController.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView+Extension.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView.swift
Labels: ✨Feature

#105 [D1] MeasurementResult 리펙토링
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Data/MeasurementResult.swift
  IKU/IKU/Manager/PersistenceManager.swift
  IKU/IKU/Manager/SQLiteService.swift
  IKU/PersistenceTest/PersistenceManagerTest.swift
  IKU/PersistenceTest/SQLiteServiceTest.swift
  IKU/PersistenceTest/String+Extension.swift
  IKU/PersistenceTest/VideoURLServiceTest.swift
  IKU/PersistenceTest/XCTestCase+Extension.swift
Labels: ♻️Refactoring

#108 [D0] MeasurementResult 변경으로 인한 영구저장소 삭제 기능 Test 변경
  IKU/PersistenceTest/PersistenceManagerTest.swift
  IKU/PersistenceTest/SQLiteServiceTest.swift
  IKU/PersistenceTest/VideoURLServiceTest.swift
Labels: ♻️Refactoring

#112 [D0] 머지 후 빌드 에러 해결
  IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVCalendarDayView.swift
Labels: 🐞Bug

#107 [D1] 아이 사진을 누르면 프로필뷰로 연결
  IKU/IKU/Views/ProfileViewController.swift
  IKU/IKU/Views/StoryView.swift
Labels: ✨Feature

#109 [D2] 영구저장소에서 영상 북마크와 가림 frame의 시간, 안가림 frame의 시간 변경 기능
  IKU/IKU/Manager/PersistenceManager.swift
  IKU/IKU/Manager/SQLiteService.swift
  IKU/PersistenceTest/PersistenceManagerTest.swift
  IKU/PersistenceTest/SQLiteServiceTest.swift
Labels: ✨Feature

#110 [D5] 영구저장소 폴더명 변경
  IKU/IKU/Manager/JSONService.swift
  IKU/IKU/Manager/VideoURLService.swift
  IKU/PersistenceTest/PersistenceManagerTest.swift
Labels: ♻️Refactoring

#115 [D1] 기록을 리스트 형식으로 확인할 수 있습니다.
  IKU/IKU/Extension/UIViewController+Extension.swift
  IKU/IKU/Storyboard/Base.lproj/Main.storyboard
  IKU/IKU/Views/HistoryListViewController.swift
  IKU/IKU/Views/ResultViewController.swift
Labels: ✨Feature

#123 [D2] 쓰레기통 버튼을 누르면 기록이 삭제된다
  IKU/IKU/Views/HistoryListViewController.swift
  IKU/IKU/Views/HistoryViewController.swift
  IKU/IKU/Views/ResultViewController.swift
Labels: ✨Feature

#127 [D0] 영어버전+탭바수정+결과뷰UI수정
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/App/Info.plist
  IKU/IKU/App/SceneDelegate.swift
  IKU/IKU/Data/TestGuideString.swift
  IKU/IKU/Extension/UIViewController+Extension.swift
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  IKU/IKU/Storyboard/Base.lproj/Main.storyboard
  IKU/IKU/Views/CoverTestViewController.swift
  IKU/IKU/Views/CoverTestViewModel.swift
  IKU/IKU/Views/HistoryViewController.swift
  IKU/IKU/Views/ProfileViewController.swift
  IKU/IKU/Views/ResultViewController.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
  IKU/IKU/Views/StoryView.swift
  IKU/IKU/Views/ViewModule/IKUChartView.swift
Labels: ♻️Refactoring

#128 [D2] StoryView 화면 변경
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Resource/Assets.xcassets/LeftEyeSelectedImage.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/LeftEyeSelectedImage.imageset/LeftEyeSelectedImage@1x.png
  IKU/IKU/Resource/Assets.xcassets/LeftEyeSelectedImage.imageset/LeftEyeSelectedImage@2x.png.png
  IKU/IKU/Resource/Assets.xcassets/LeftEyeSelectedImage.imageset/LeftEyeSelectedImage@3x.png.png
  IKU/IKU/Resource/Assets.xcassets/RightEyeSelectedImage.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/RightEyeSelectedImage.imageset/RightEyeSelectedImage@1.png
  IKU/IKU/Resource/Assets.xcassets/RightEyeSelectedImage.imageset/RightEyeSelectedImage@2.png
  IKU/IKU/Resource/Assets.xcassets/RightEyeSelectedImage.imageset/RightEyeSelectedImage@3.png
  IKU/IKU/Resource/Assets.xcassets/lefteye.imageset/lefteye.png
  IKU/IKU/Resource/Assets.xcassets/righteye.imageset/righteye.png
  IKU/IKU/Views/SelectWhichEyeView.swift
  IKU/IKU/Views/StoryView.swift
Labels: ♻️Refactoring

#134 [D1] ScrubberView가 정확한 위치를 가리키고, 전체 Video를 담도록 수정
  IKU/IKU/Views/ScrubberView.swift
Labels: 🐞Bug

#129 [D2] 북마크 기능을 사용할 수 있습니다.
  IKU/IKU/Views/HistoryListViewController.swift
  IKU/IKU/Views/ResultViewController.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVCalendarDayView.swift
Labels: ✨Feature

#106 [D2] Color 정리
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/App/SceneDelegate.swift
  IKU/IKU/Extension/Color+Extension.swift
  IKU/IKU/Extension/UIColor+Extension.swift
  IKU/IKU/Resource/Color.xcassets/ikuActiveRed.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuBackgroundBlue.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuBlue.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuButtonGray.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuCameraYellow.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuDeactiveRed.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuDefaultBlack.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuDefaultWhite.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuEyeSelectBackgroundBlue.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuPopUpBackgroundBlack.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuPopUpBlue.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuPopUpGray.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuResultGray.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuResultGreen.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuResultLightGreen.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuResultLightRed.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuResultLightYellow.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuResultRed.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuResultYellow.colorset/Contents.json
  IKU/IKU/Resource/Color.xcassets/ikuTestBackgroundBlack.colorset/Contents.json
  IKU/IKU/Views/CoverTestViewModel.swift
  IKU/IKU/Views/DictionaryViewController.swift
  IKU/IKU/Views/HistoryListViewController.swift
  IKU/IKU/Views/HistoryViewController.swift
  IKU/IKU/Views/ProfileViewController.swift
  IKU/IKU/Views/SelectWhichEyeView.swift
  IKU/IKU/Views/StoryView.swift
  IKU/IKU/Views/ViewController.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView.swift
Labels: ♻️Refactoring

#135 [D1] 검사 결과 화면 기능 추가
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Storyboard/Base.lproj/Main.storyboard
  IKU/IKU/Views/CoverTestViewController.swift
  IKU/IKU/Views/CoverTestViewModel.swift
  IKU/IKU/Views/HistoryViewController.swift
  IKU/IKU/Views/ResultViewController.swift
  IKU/IKU/Views/StoryView.swift
Labels: ✨Feature

#142 [D0] 유닛테스트 첫 1회 실패 버그
  IKU/PersistenceTest/PersistenceManagerTest.swift
Labels: 🐞Bug

#139 [D2] Tabbar UI 변경, NavigationBackButton UI 변경
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/App/SceneDelegate.swift
  IKU/IKU/Extension/ExtensionPlaceholder.swift
  IKU/IKU/Extension/UINavigationController+Extension.swift
  IKU/IKU/Resource/Assets.xcassets/StrabismusTestIcon.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/StrabismusTestIcon.imageset/StrabismusTestIcon@1x.png
  IKU/IKU/Resource/Assets.xcassets/StrabismusTestIcon.imageset/StrabismusTestIcon@2x.png
  IKU/IKU/Resource/Assets.xcassets/StrabismusTestIcon.imageset/StrabismusTestIcon@3x.png
Labels: ♻️Refactoring

#143 [D1] 아이 정보를 저장할 수 있는 영구저장소 구조 설계
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Manager/PersistenceManager.swift
  IKU/IKU/Manager/SQLiteService.swift
  IKU/PersistenceTest/PersistenceManagerTest.swift
  IKU/PersistenceTest/SQLiteServiceTest.swift
Labels: ✨Feature

#148 [D1] 프로필 정보를 저장하고 수정할 수 있습니다.
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Data/UserdefaultKey.swift
  IKU/IKU/Manager/PHPhotoManager.swift
  IKU/IKU/Resource/Assets.xcassets/DefaultProfileImage.imageset/AppIcon.png
  IKU/IKU/Resource/Assets.xcassets/DefaultProfileImage.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/coverEye.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/coverEye.imageset/coverEye.png
  IKU/IKU/Resource/Assets.xcassets/uncoverEye.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/uncoverEye.imageset/uncoverEye.png
  IKU/IKU/Views/ProfileViewController.swift
  IKU/IKU/Views/StoryView.swift
Labels: ✨Feature

#150 [D1] 런치스크린을 추가하였습니다.
  IKU/IKU/App/Base.lproj/LaunchScreen.storyboard
  IKU/IKU/Resource/Assets.xcassets/LaunchScreen_Icon.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/LaunchScreen_Icon.imageset/LaunchScreen_Icon.png
Labels: ✨Feature

#154 [D1] AR 노드의 투명도를 조절하였습니다.
  IKU/IKU/Resource/Models.scnassets/coordinateOrigin.scn
Labels: ♻️Refactoring
