Repository DeveloperAcademy-POSTECH/MacC-Team-IKU, pull requests merged in 2022-12, with the labels that each got.

#157 [D1] Frame 추천 기능
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Views/CoverTestViewController.swift
  IKU/IKU/Views/NavigationViewController.swift
  IKU/IKU/Views/ScrubberView.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
  IKU/IKU/Views/SpeechBubbleView.swift
Labels: ✨Feature

#160 [D1] Cover Test View Update
  IKU/IKU/Data/TestGuideString.swift
  IKU/IKU/Resource/Assets.xcassets/Left_Test_HandGuide.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/Left_Test_HandGuide.imageset/Left_Test_HandGuide.png
  IKU/IKU/Resource/Assets.xcassets/Right_Test_HandGuide.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/Right_Test_HandGuide.imageset/Right_Test_HandGuide.png
  IKU/IKU/Storyboard/Base.lproj/Main.storyboard
  IKU/IKU/Views/CoverTestViewController.swift
  IKU/IKU/Views/CoverTestViewModel.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView+Extension.swift
  IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView.swift
Labels: ♻️Refactoring

#163 [D1] ResultView UI Update
  IKU/IKU/Storyboard/Base.lproj/Main.storyboard
  IKU/IKU/Views/CoverTestViewController.swift
  IKU/IKU/Views/HistoryListViewController.swift
  IKU/IKU/Views/ResultViewController.swift
Labels: ♻️Refactoring

#166 [D1] What should I do? 버튼
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Extension/UIColor+Extension.swift
  IKU/IKU/Resource/Assets.xcassets/GuideImage_0.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/GuideImage_0.imageset/GuideImage_0.png
  IKU/IKU/Resource/Assets.xcassets/GuideImage_0.imageset/GuideImage_0@2x.png
  IKU/IKU/Resource/Assets.xcassets/GuideImage_0.imageset/GuideImage_0@3x.png
  IKU/IKU/Resource/Assets.xcassets/GuideImage_1.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/GuideImage_1.imageset/GuideImage_1.png
  IKU/IKU/Resource/Assets.xcassets/GuideImage_1.imageset/GuideImage_1@2x.png
  IKU/IKU/Resource/Assets.xcassets/GuideImage_1.imageset/GuideImage_1@3x.png
  IKU/IKU/Resource/Color.xcassets/ikuWhatBlue.colorset/Contents.json
  IKU/IKU/Views/CareGuideView.swift
  IKU/IKU/Views/ResultViewController.swift
Labels: ✨Feature

#161 [D1] 가림막 검사에 대한 설명 버튼
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Extension/UIImage+Extension.swift
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest1.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest1.imageset/Group 3682.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest1.imageset/Group 3682@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest1.imageset/Group 3682@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest10.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest10.imageset/Group 3697.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest10.imageset/Group 3697@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest10.imageset/Group 3697@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest11.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest11.imageset/Group 3698.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest11.imageset/Group 3698@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest11.imageset/Group 3698@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest2.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest2.imageset/Group 3673.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest2.imageset/Group 3673@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest2.imageset/Group 3673@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest3.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest3.imageset/Group 3683.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest3.imageset/Group 3683@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest3.imageset/Group 3683@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest4.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest4.imageset/Group 3691.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest4.imageset/Group 3691@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest4.imageset/Group 3691@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest5.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest5.imageset/Group 3692.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest5.imageset/Group 3692@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest5.imageset/Group 3692@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest6.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest6.imageset/Group 3693.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest6.imageset/Group 3693@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest6.imageset/Group 3693@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest7.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest7.imageset/Group 3694.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest7.imageset/Group 3694@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest7.imageset/Group 3694@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest8.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest8.imageset/Group 3695.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest8.imageset/Group 3695@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest8.imageset/Group 3695@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest9.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest9.imageset/Group 3696.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest9.imageset/Group 3696@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest9.imageset/Group 3696@3x.png
  IKU/IKU/Resource/WhatIsCoverTest1.gif
  IKU/IKU/Resource/WhatIsCoverTest3.gif
  IKU/IKU/Views/GIFImageView.swift
  IKU/IKU/Views/StoryView.swift
  IKU/IKU/Views/WhatIsCoverTestView.swift
Labels: ✨Feature

#167 [D1] Navigation Title in ProfileView
  IKU/IKU/Views/ProfileViewController.swift
Labels: ♻️Refactoring

#164 [D3] README.md 수정
  README.md
Labels: 📝Docs

#170 [D0] 눈 방향 값을 정상적으로 전달합니다.
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/100.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/144.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/152.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/167.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/20.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/50.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/72.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/76.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  IKU/IKU/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  IKU/IKU/Resource/Font/NEXON_Lv1_Gothic_OTF.otf
  IKU/IKU/Resource/Font/NEXON_Lv1_Gothic_OTF_Bold.otf
  IKU/IKU/Resource/Font/NEXON_Lv1_Gothic_OTF_Light.otf
  IKU/IKU/Storyboard/Base.lproj/Main.storyboard
  IKU/IKU/Views/HistoryListViewController.swift
  IKU/IKU/Views/HistoryViewController.swift
  IKU/IKU/Views/ResultViewController.swift
Labels: ♻️Refactoring

#168 [D3] Refactor Image assets
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest4.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest4.imageset/Group 3691.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest4.imageset/Group 3691@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest4.imageset/Group 3691@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest4.imageset/Group 3702.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest4.imageset/Group 3702@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest4.imageset/Group 3702@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest5.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest5.imageset/Group 3692.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest5.imageset/Group 3692@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest5.imageset/Group 3692@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest5.imageset/Group 3703.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest5.imageset/Group 3703@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest5.imageset/Group 3703@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest6.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest6.imageset/Group 3693.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest6.imageset/Group 3693@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest6.imageset/Group 3693@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest6.imageset/Group 3704.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest6.imageset/Group 3704@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest6.imageset/Group 3704@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest7.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest7.imageset/Group 3694.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest7.imageset/Group 3694@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest7.imageset/Group 3694@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest7.imageset/Group 3705.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest7.imageset/Group 3705@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest7.imageset/Group 3705@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest8.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest8.imageset/Group 3695.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest8.imageset/Group 3695@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest8.imageset/Group 3695@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest8.imageset/Group 3706.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest8.imageset/Group 3706@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest8.imageset/Group 3706@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest9.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest9.imageset/Group 3696.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest9.imageset/Group 3696@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest9.imageset/Group 3696@3x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest9.imageset/Group 3707.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest9.imageset/Group 3707@2x.png
  IKU/IKU/Resource/Assets.xcassets/WhatIsCoverTest9.imageset/Group 3707@3x.png
Labels: ♻️Refactoring

#173 [D1] 동영상 다시 보기 버튼
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Storyboard/Base.lproj/Main.storyboard
  IKU/IKU/Views/HistoryViewController.swift
  IKU/IKU/Views/ResultViewController.swift
  IKU/IKU/Views/ScrubberView.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
Labels: ✨Feature

#175 [D1] 영어문구 수정 및 UI 변경
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Data/StrabismusLog.swift
  IKU/IKU/Data/TestGuideString.swift
  IKU/IKU/Extension/UIViewController+Extension.swift
  IKU/IKU/Views/CareGuideView.swift
  IKU/IKU/Views/CoverTestViewModel.swift
  IKU/IKU/Views/HistoryListViewController.swift
  IKU/IKU/Views/ProfileViewController.swift
  IKU/IKU/Views/ResultViewController.swift
  IKU/IKU/Views/SelectPhotoViewController.swift
  IKU/IKU/Views/StoryView.swift
  IKU/IKU/Views/ViewModule/IKUChartView.swift
Labels: ♻️Refactoring

#176 [D1] 사시 검사 화면에서 눈 선택 View를 조금 더 Figma와 비슷하게 변경
  IKU/IKU/Views/StoryView.swift
Labels: ✨Feature

#174 [D1] What is cover test GIF 화질 개선
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Resource/WhatIsCoverTest1.gif
  IKU/IKU/Resource/WhatIsCoverTest3.gif
  IKU/IKU/Views/WhatIsCoverTestView.swift
Labels: ♻️Refactoring

#178 [D0] 다크모드 Disable
  IKU/IKU/App/SceneDelegate.swift
Labels: 🐞Bug

#180 [D0] Frame 선택 화면 무한 반복 버그 해결
  IKU/IKU/Views/SelectPhotoViewController.swift
Labels: 🐞Bug

#182 [D0] Chart Title 문구 변경
  IKU/IKU/Views/ViewModule/IKUChartView.swift
Labels: ♻️Refactoring

#187 What is Cover Test의 6, 8번 사진을 정상적으로 표시합니다.
  IKU/IKU/Views/WhatIsCoverTestView.swift
Labels: 🐞Bug, ♻️Refactoring

#189 [D0] 결과화면 오류 수정
  IKU/IKU/Views/ResultViewController.swift
Labels: 🐞Bug, ♻️Refactoring

#195 [D0] CoverTestView 에 초점 아이콘을 추가합니다.
  IKU/IKU/Resource/Assets.xcassets/FocusIcon.imageset/Contents.json
  IKU/IKU/Resource/Assets.xcassets/FocusIcon.imageset/FocusIcon.png
  IKU/IKU/Storyboard/Base.lproj/Main.storyboard
  IKU/IKU/Views/CoverTestViewController.swift
  IKU/IKU/Views/CoverTestViewModel.swift
  IKU/IKU/Views/ResultViewController.swift
Labels: ✨Feature

#198 [D1] What is cover test GIF 화질 개선
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Resource/WhatIsCoverTest1.gif
  IKU/IKU/Resource/WhatIsCoverTest3.gif
Labels: ♻️Refactoring

#197 [D1] 다시보기 버튼 UI 변경
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Storyboard/Base.lproj/Main.storyboard
Labels: ♻️Refactoring

#199 [D3] README.md 수정
  README.md
Labels: ♻️Refactoring

#200 [D5] 미사용 파일 제거
  IKU/IKU.xcodeproj/project.pbxproj
  IKU/IKU/Delegate(Protocol)/Placeholder.swift
  IKU/IKU/Manager/ManagerPlaceholder.swift
  IKU/IKU/Views/NavigationViewController.swift
  IKU/IKU/Views/StoryViewController.swift
  IKU/IKU/Views/ViewController.swift
Labels: ♻️Refactoring
